jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      uses: fossas/fossa-action@v1
      with:
        api-key: ${{secrets.fossaApiKey}}
        run-tests: true
